version: '3.8'

services:
  kodskog-fe:
    build:
      context: ./Kodskog-FE/homepage
    container_name: kodskog-fe
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=cIAHPb/v8Im9F3e7q4uyBGm7MnG9aAezB8YWOkEEOiA=
      - MOVIEFLEX_API_URL=http://kodskog-movieflex:10123
      - ACCOUNT_MANAGER_URL=http://kodskog-oakauth:5000
    ports:
      - "3000:3000"
    networks:
      - frontend-network
      - backend-network
  
  kodskog-traffic-logger:
    build: ./Kodskog-BE/logger/
    container_name: traffic-logger
    ports:
      - "5001:5000"
    volumes:
      - traffic-log:/app/logs
    networks:
      - backend-network


  kodskog-oakauth:
    build: ./Kodskog-BE/API/
    container_name: oakauth
    depends_on:
      - kodskog-traffic-logger
    environment:
      LOGGER_API_URL: "http://kodskog-traffic-logger:5000"
    ports:
      - "5000:5000"
    networks:
      - backend-network

  kodskog-postgres-mf:
    build:
      context: ./Kodskog-MovieFlex/db
    container_name: kodskog-mf-db-v1
    environment:
      - POSTGRES_DB=moviedb
      - POSTGRES_USER=movieuser
      - POSTGRES_PASSWORD=moviepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-mf-data:/var/lib/postgresql/data
    networks:
      - movieflex-network
      - backend-network

  kodskog-postgres-mf-fetch:
    build:
      context: ./Kodskog-MovieFlex/db/fetch
    container_name: postgres-mf-fetch-v1
    environment:
      - DB_URL=jdbc:postgresql://kodskog-postgres-mf:5432/moviedb
      - DB_USER=movieuser
      - DB_PASSWORD=moviepassword
    depends_on:
      - kodskog-postgres-mf
    networks:
      - movieflex-network
      - backend-network

  kodskog-movieflex:
    build:
      context: ./Kodskog-MovieFlex/moveiflex
    container_name: kodskog-mf
    environment:
      - DB_HOST=kodskog-postgres-mf
      - DB_PORT=5432
      - DB_NAME=moviedb
      - DB_USERNAME=movieuser
      - DB_PASSWORD=moviepassword
    ports:
      - "10123:10123"
    depends_on:
      - kodskog-postgres-mf
      - kodskog-postgres-mf-fetch
    networks:
      - movieflex-network
      - backend-network

volumes:
  postgres-mf-data:
  oakauth:
  traffic-log:
  moveiflex:

networks:
  frontend-network:
  movieflex-network:
  backend-network:
    driver: bridge
