version: '3.8'

services:
  kodskog-fe:
    build:
      context: ./Kodskog-FE/homepage
    container_name: kodskog-fe
    environment:
      - KEYCLOAK_CLIENT_ID=kodskog
      - KEYCLOAK_CLIENT_SECRET=BeJ2THx2xJk9UThtpZEFBs5XYgDMkOV8
      - KEYCLOAK_ISSUER=http://kodskog-keycloak:8080/realms/kodskog
      - END_SESSION_URL=http://kodskog-keycloak/realms/Kodskog/protocol/openid-connect/logout
      - REFRESH_TOKEN_URL=http://kodskog-keycloak/realms/Kodskog/protocol/openid-connect/token
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=cIAHPb/v8Im9F3e7q4uyBGm7MnG9aAezB8YWOkEEOiA=
    ports:
      - "3000:3000"
    networks:
      - frontend-network
      - keycloak-network

  kodskog-keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql 
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    command:
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/opt/jboss/keycloak/import"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    ports:
      - 8080:8080
    volumes:
      - "./docker/import_realm_users:/opt/jboss/keycloak/import"
    depends_on:
      - keycloak-mysql
    networks:
      - keycloak-network

  keycloak-mysql:
    image: mysql:latest
    container_name: keycloak-mysql
    volumes:
      - keycloak-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    networks:
      - keycloak-network

  kodskog-movieflex:
    build:
      context: ./Kodskog-MovieFlex/moveiflex
    container_name: kodskog-mf
    environment:
      - DB_HOST=postgres-mf
      - DB_PORT=5432
      - DB_NAME=moviedb
      - DB_USERNAME=movieuser
      - DB_PASSWORD=moviepassword
      - KEYCLOAK_CLIENT_ID=kodskog
      - KEYCLOAK_CLIENT_SECRET=BeJ2THx2xJk9UThtpZEFBs5XYgDMkOV8
      - KEYCLOAK_AUTH_SERVER_URL=http://kodskog-keycloak:8080/auth
    ports:
      - "10123:10123"
    depends_on:
      - postgres-mf
      - postgres-mf-fetch
    networks:
      - movieflex-network
      - keycloak-network

  postgres-mf:
    build:
      context: ./Kodskog-MovieFlex/db
    container_name: kodskog-mf-db-v1
    environment:
      - POSTGRES_DB=moviedb
      - POSTGRES_USER=movieuser
      - POSTGRES_PASSWORD=moviepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-mf-data:/var/lib/postgresql/data
    networks:
      - movieflex-network
      - keycloak-network

  postgres-mf-fetch:
    build:
      context: ./Kodskog-MovieFlex/db/fetch
    container_name: postgres-mf-fetch-v1
    environment:
      - DB_URL=jdbc:postgresql://postgres-mf:5432/moviedb
      - DB_USER=movieuser
      - DB_PASSWORD=moviepassword
    depends_on:
      - postgres-mf
    networks:
      - movieflex-network
      - keycloak-network

volumes:
  keycloak-mysql-data:
  postgres-mf-data:

networks:
  frontend-network:
  movieflex-network:
  keycloak-network:
    driver: bridge
