# Create a ConfigMap to store environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: kodskog-config
  namespace: fe
data:
  KEYCLOAK_CLIENT_ID: "kodskog"
  KEYCLOAK_CLIENT_SECRET: "YxU3SKx78qfGVWyHQLNl4LLyNegYM8pA"
  KEYCLOAK_ISSUER: "http://kodskog-keycloak-service.iam.svc.cluster.local:8080/realms/kodskog"
  END_SESSION_URL: "http://kodskog-keycloak-service.iam.svc.cluster.local:8080/realms/kodskog/protocol/openid-connect/logout"
  REFRESH_TOKEN_URL: "http://kodskog-keycloak-service.iam.svc.cluster.local:8080/realms/kodskog/protocol/openid-connect/token"
  NEXTAUTH_URL: http://localhost:3000
  NEXTAUTH_SECRET: "cIAHPb/v8Im9F3e7q4uyBGm7MnG9aAezB8YWOkEEOiA="
  MOVIEFLEX_API_URL: http://localhost:10123
  ACCOUNT_MANAGER_URL: "http://account-manager-service.iam.svc.cluster.local:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: kodskog-fe-service
  namespace: fe
spec:
  selector:
    app: kodskog-fe
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodskog-fe-deployment
  namespace: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kodskog-fe
  template:
    metadata:
      labels:
        app: kodskog-fe
    spec:
      containers:
      - name: kodskog-fe
        image: hadisaghir/kodskog-fe:v2
        ports:
        - containerPort: 3000
        env:
        - name: MOVIEFLEX_API_URL
          valueFrom:
            configMapKeyRef:
              name: kodskog-config
              key: MOVIEFLEX_API_URL
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: kodskog-config
              key: NEXTAUTH_URL
        - name: NEXTAUTH_SECRET
          valueFrom:
            configMapKeyRef:
              name: kodskog-config
              key: NEXTAUTH_SECRET
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: kodskog-config
              key: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: kodskog-config
              key: KEYCLOAK_CLIENT_SECRET
        - name: KEYCLOAK_ISSUER
          valueFrom:
            configMapKeyRef:
              name: kodskog-config
              key: KEYCLOAK_ISSUER
        - name: END_SESSION_URL
          valueFrom:
            configMapKeyRef:
              name: kodskog-config
              key: END_SESSION_URL
        - name: REFRESH_TOKEN_URL
          valueFrom:
            configMapKeyRef:
              name: kodskog-config
              key: REFRESH_TOKEN_URL
        - name: ACCOUNT_MANAGER_URL
          valueFrom:
            configMapKeyRef:
              name: kodskog-config
              key: ACCOUNT_MANAGER_URL
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kodskog-fe-ingress
  namespace: fe
spec:
  rules:
  - host: hadisaghir.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kodskog-fe-service
            port:
              number: 3000

