version: '3.8'

services:
  postgres-mf:
    build:
      context: ./db  # Directory containing the custom Dockerfile for PostgreSQL
    container_name: kodskog-mf-db-v1
    ports:
      - "5432:5432"
    networks:
      - movie-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  populate:
    build:
      context: ./db/fetch  # Directory containing the Dockerfile for the "fetch-ids" service
    container_name: kodskog-mf-db-fetch-v1
    depends_on:
      - postgresmf
    networks:
      - movie-network
      
  movieflex:
    build:
      context: ./moveiflex  # Directory containing the Dockerfile for the "moveiflex" project
    container_name: kodskog-mf-v1
    depends_on:
      - postgresmf
      - populate
    ports:
      - "10123:10123"
    networks:
      - movie-network

volumes:
  postgres-data:

networks:
  movie-network: