version: '3.8'

services:
  kodskog-postgres-mf:
    build:
      context: ./db
    container_name: kodskog-mf-db-v1
    environment:
      - POSTGRES_DB=moviedb
      - POSTGRES_USER=movieuser
      - POSTGRES_PASSWORD=moviepassword
    ports:
      - "5432:5432"
    networks:
      - movieflex-network

  kodskog-postgres-mf-fetch:
    build:
      context: ./db/fetch
    container_name: postgres-mf-fetch-v1
    environment:
      - DB_URL=jdbc:postgresql://kodskog-postgres-mf:5432/moviedb
      - DB_USER=movieuser
      - DB_PASSWORD=moviepassword
    depends_on:
      - kodskog-postgres-mf
    networks:
      - movieflex-network

  kodskog-movieflex:
    build:
      context: ./moveiflex
    container_name: kodskog-mf
    environment:
      - DB_HOST=kodskog-postgres-mf
      - DB_PORT=5432
      - DB_NAME=moviedb
      - DB_USERNAME=movieuser
      - DB_PASSWORD=moviepassword
    ports:
      - "10123:10123"
    depends_on:
      - kodskog-postgres-mf
      - kodskog-postgres-mf-fetch
    networks:
      - movieflex-network

networks:
  movieflex-network: